/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ManagerTeamRouteImport } from './routes/manager.team'
import { Route as ManagerTasksRouteImport } from './routes/manager.tasks'
import { Route as ManagerProjectsRouteImport } from './routes/manager.projects'
import { Route as ManagerDashboardRouteImport } from './routes/manager.dashboard'
import { Route as ManagerAnalyticsRouteImport } from './routes/manager.analytics'
import { Route as EmployeeTimesheetRouteImport } from './routes/employee.timesheet'
import { Route as EmployeeTeamRouteImport } from './routes/employee.team'
import { Route as EmployeeTasksRouteImport } from './routes/employee.tasks'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeeGamesRouteImport } from './routes/employee.games'
import { Route as EmployeeDashboardRouteImport } from './routes/employee.dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ManagerDeliverablesIndexRouteImport } from './routes/manager.deliverables.index'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin.employees.index'
import { Route as AdminDeliverablesIndexRouteImport } from './routes/admin.deliverables.index'
import { Route as EmployeeTasksTaskIdRouteImport } from './routes/employee.tasks_.$taskId'
import { Route as AdminEmployeesRolesRouteImport } from './routes/admin.employees.roles'
import { Route as AdminDeliverablesIdRouteImport } from './routes/admin.deliverables.$id'
import { Route as AdminClientsNewRouteImport } from './routes/admin.clients_.new'
import { Route as ManagerProjectsIdSetupRouteImport } from './routes/manager.projects_.$id.setup'
import { Route as ManagerAnalyticsEmployeeIdRouteImport } from './routes/manager.analytics_.employee.$id'
import { Route as AdminEmployeesRolesNewRouteImport } from './routes/admin.employees.roles_.new'
import { Route as AdminEmployeesRolesIdRouteImport } from './routes/admin.employees.roles_.$id'
import { Route as AdminDeliverablesClientsIdRouteImport } from './routes/admin.deliverables.clients.$id'
import { Route as AdminAnalyticsEmployeeIdRouteImport } from './routes/admin.analytics_.employee.$id'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTasksRoute = ManagerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerProjectsRoute = ManagerProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeTimesheetRoute = EmployeeTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTeamRoute = EmployeeTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeGamesRoute = EmployeeGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerDeliverablesIndexRoute =
  ManagerDeliverablesIndexRouteImport.update({
    id: '/deliverables/',
    path: '/deliverables/',
    getParentRoute: () => ManagerRoute,
  } as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const AdminDeliverablesIndexRoute = AdminDeliverablesIndexRouteImport.update({
  id: '/deliverables/',
  path: '/deliverables/',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeTasksTaskIdRoute = EmployeeTasksTaskIdRouteImport.update({
  id: '/tasks_/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminEmployeesRolesRoute = AdminEmployeesRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const AdminDeliverablesIdRoute = AdminDeliverablesIdRouteImport.update({
  id: '/deliverables/$id',
  path: '/deliverables/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/clients_/new',
  path: '/clients/new',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerProjectsIdSetupRoute = ManagerProjectsIdSetupRouteImport.update({
  id: '/projects_/$id/setup',
  path: '/projects/$id/setup',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAnalyticsEmployeeIdRoute =
  ManagerAnalyticsEmployeeIdRouteImport.update({
    id: '/analytics_/employee/$id',
    path: '/analytics/employee/$id',
    getParentRoute: () => ManagerRoute,
  } as any)
const AdminEmployeesRolesNewRoute = AdminEmployeesRolesNewRouteImport.update({
  id: '/roles_/new',
  path: '/roles/new',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const AdminEmployeesRolesIdRoute = AdminEmployeesRolesIdRouteImport.update({
  id: '/roles_/$id',
  path: '/roles/$id',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const AdminDeliverablesClientsIdRoute =
  AdminDeliverablesClientsIdRouteImport.update({
    id: '/deliverables/clients/$id',
    path: '/deliverables/clients/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsEmployeeIdRoute =
  AdminAnalyticsEmployeeIdRouteImport.update({
    id: '/analytics_/employee/$id',
    path: '/analytics/employee/$id',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/games': typeof EmployeeGamesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/employee/team': typeof EmployeeTeamRoute
  '/employee/timesheet': typeof EmployeeTimesheetRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/projects': typeof ManagerProjectsRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/deliverables/$id': typeof AdminDeliverablesIdRoute
  '/admin/employees/roles': typeof AdminEmployeesRolesRoute
  '/employee/tasks/$taskId': typeof EmployeeTasksTaskIdRoute
  '/admin/deliverables/': typeof AdminDeliverablesIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/manager/deliverables/': typeof ManagerDeliverablesIndexRoute
  '/admin/analytics/employee/$id': typeof AdminAnalyticsEmployeeIdRoute
  '/admin/deliverables/clients/$id': typeof AdminDeliverablesClientsIdRoute
  '/admin/employees/roles/$id': typeof AdminEmployeesRolesIdRoute
  '/admin/employees/roles/new': typeof AdminEmployeesRolesNewRoute
  '/manager/analytics/employee/$id': typeof ManagerAnalyticsEmployeeIdRoute
  '/manager/projects/$id/setup': typeof ManagerProjectsIdSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/games': typeof EmployeeGamesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/employee/team': typeof EmployeeTeamRoute
  '/employee/timesheet': typeof EmployeeTimesheetRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/projects': typeof ManagerProjectsRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/deliverables/$id': typeof AdminDeliverablesIdRoute
  '/admin/employees/roles': typeof AdminEmployeesRolesRoute
  '/employee/tasks/$taskId': typeof EmployeeTasksTaskIdRoute
  '/admin/deliverables': typeof AdminDeliverablesIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/manager/deliverables': typeof ManagerDeliverablesIndexRoute
  '/admin/analytics/employee/$id': typeof AdminAnalyticsEmployeeIdRoute
  '/admin/deliverables/clients/$id': typeof AdminDeliverablesClientsIdRoute
  '/admin/employees/roles/$id': typeof AdminEmployeesRolesIdRoute
  '/admin/employees/roles/new': typeof AdminEmployeesRolesNewRoute
  '/manager/analytics/employee/$id': typeof ManagerAnalyticsEmployeeIdRoute
  '/manager/projects/$id/setup': typeof ManagerProjectsIdSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/games': typeof EmployeeGamesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/employee/team': typeof EmployeeTeamRoute
  '/employee/timesheet': typeof EmployeeTimesheetRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/manager/projects': typeof ManagerProjectsRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/admin/clients_/new': typeof AdminClientsNewRoute
  '/admin/deliverables/$id': typeof AdminDeliverablesIdRoute
  '/admin/employees/roles': typeof AdminEmployeesRolesRoute
  '/employee/tasks_/$taskId': typeof EmployeeTasksTaskIdRoute
  '/admin/deliverables/': typeof AdminDeliverablesIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/manager/deliverables/': typeof ManagerDeliverablesIndexRoute
  '/admin/analytics_/employee/$id': typeof AdminAnalyticsEmployeeIdRoute
  '/admin/deliverables/clients/$id': typeof AdminDeliverablesClientsIdRoute
  '/admin/employees/roles_/$id': typeof AdminEmployeesRolesIdRoute
  '/admin/employees/roles_/new': typeof AdminEmployeesRolesNewRoute
  '/manager/analytics_/employee/$id': typeof ManagerAnalyticsEmployeeIdRoute
  '/manager/projects_/$id/setup': typeof ManagerProjectsIdSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/projects'
    | '/admin/settings'
    | '/employee/dashboard'
    | '/employee/games'
    | '/employee/notifications'
    | '/employee/tasks'
    | '/employee/team'
    | '/employee/timesheet'
    | '/manager/analytics'
    | '/manager/dashboard'
    | '/manager/projects'
    | '/manager/tasks'
    | '/manager/team'
    | '/admin/'
    | '/employee/'
    | '/manager/'
    | '/admin/clients/new'
    | '/admin/deliverables/$id'
    | '/admin/employees/roles'
    | '/employee/tasks/$taskId'
    | '/admin/deliverables/'
    | '/admin/employees/'
    | '/manager/deliverables/'
    | '/admin/analytics/employee/$id'
    | '/admin/deliverables/clients/$id'
    | '/admin/employees/roles/$id'
    | '/admin/employees/roles/new'
    | '/manager/analytics/employee/$id'
    | '/manager/projects/$id/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/projects'
    | '/admin/settings'
    | '/employee/dashboard'
    | '/employee/games'
    | '/employee/notifications'
    | '/employee/tasks'
    | '/employee/team'
    | '/employee/timesheet'
    | '/manager/analytics'
    | '/manager/dashboard'
    | '/manager/projects'
    | '/manager/tasks'
    | '/manager/team'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/clients/new'
    | '/admin/deliverables/$id'
    | '/admin/employees/roles'
    | '/employee/tasks/$taskId'
    | '/admin/deliverables'
    | '/admin/employees'
    | '/manager/deliverables'
    | '/admin/analytics/employee/$id'
    | '/admin/deliverables/clients/$id'
    | '/admin/employees/roles/$id'
    | '/admin/employees/roles/new'
    | '/manager/analytics/employee/$id'
    | '/manager/projects/$id/setup'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/projects'
    | '/admin/settings'
    | '/employee/dashboard'
    | '/employee/games'
    | '/employee/notifications'
    | '/employee/tasks'
    | '/employee/team'
    | '/employee/timesheet'
    | '/manager/analytics'
    | '/manager/dashboard'
    | '/manager/projects'
    | '/manager/tasks'
    | '/manager/team'
    | '/admin/'
    | '/employee/'
    | '/manager/'
    | '/admin/clients_/new'
    | '/admin/deliverables/$id'
    | '/admin/employees/roles'
    | '/employee/tasks_/$taskId'
    | '/admin/deliverables/'
    | '/admin/employees/'
    | '/manager/deliverables/'
    | '/admin/analytics_/employee/$id'
    | '/admin/deliverables/clients/$id'
    | '/admin/employees/roles_/$id'
    | '/admin/employees/roles_/new'
    | '/manager/analytics_/employee/$id'
    | '/manager/projects_/$id/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/tasks': {
      id: '/manager/tasks'
      path: '/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof ManagerTasksRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/projects': {
      id: '/manager/projects'
      path: '/projects'
      fullPath: '/manager/projects'
      preLoaderRoute: typeof ManagerProjectsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/analytics': {
      id: '/manager/analytics'
      path: '/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/timesheet': {
      id: '/employee/timesheet'
      path: '/timesheet'
      fullPath: '/employee/timesheet'
      preLoaderRoute: typeof EmployeeTimesheetRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/team': {
      id: '/employee/team'
      path: '/team'
      fullPath: '/employee/team'
      preLoaderRoute: typeof EmployeeTeamRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/tasks': {
      id: '/employee/tasks'
      path: '/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/games': {
      id: '/employee/games'
      path: '/games'
      fullPath: '/employee/games'
      preLoaderRoute: typeof EmployeeGamesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/deliverables/': {
      id: '/manager/deliverables/'
      path: '/deliverables'
      fullPath: '/manager/deliverables/'
      preLoaderRoute: typeof ManagerDeliverablesIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/deliverables/': {
      id: '/admin/deliverables/'
      path: '/deliverables'
      fullPath: '/admin/deliverables/'
      preLoaderRoute: typeof AdminDeliverablesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/tasks_/$taskId': {
      id: '/employee/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/employee/tasks/$taskId'
      preLoaderRoute: typeof EmployeeTasksTaskIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/employees/roles': {
      id: '/admin/employees/roles'
      path: '/roles'
      fullPath: '/admin/employees/roles'
      preLoaderRoute: typeof AdminEmployeesRolesRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/deliverables/$id': {
      id: '/admin/deliverables/$id'
      path: '/deliverables/$id'
      fullPath: '/admin/deliverables/$id'
      preLoaderRoute: typeof AdminDeliverablesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients_/new': {
      id: '/admin/clients_/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/projects_/$id/setup': {
      id: '/manager/projects_/$id/setup'
      path: '/projects/$id/setup'
      fullPath: '/manager/projects/$id/setup'
      preLoaderRoute: typeof ManagerProjectsIdSetupRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/analytics_/employee/$id': {
      id: '/manager/analytics_/employee/$id'
      path: '/analytics/employee/$id'
      fullPath: '/manager/analytics/employee/$id'
      preLoaderRoute: typeof ManagerAnalyticsEmployeeIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/admin/employees/roles_/new': {
      id: '/admin/employees/roles_/new'
      path: '/roles/new'
      fullPath: '/admin/employees/roles/new'
      preLoaderRoute: typeof AdminEmployeesRolesNewRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/employees/roles_/$id': {
      id: '/admin/employees/roles_/$id'
      path: '/roles/$id'
      fullPath: '/admin/employees/roles/$id'
      preLoaderRoute: typeof AdminEmployeesRolesIdRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/deliverables/clients/$id': {
      id: '/admin/deliverables/clients/$id'
      path: '/deliverables/clients/$id'
      fullPath: '/admin/deliverables/clients/$id'
      preLoaderRoute: typeof AdminDeliverablesClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics_/employee/$id': {
      id: '/admin/analytics_/employee/$id'
      path: '/analytics/employee/$id'
      fullPath: '/admin/analytics/employee/$id'
      preLoaderRoute: typeof AdminAnalyticsEmployeeIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminEmployeesRouteChildren {
  AdminEmployeesRolesRoute: typeof AdminEmployeesRolesRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminEmployeesRolesIdRoute: typeof AdminEmployeesRolesIdRoute
  AdminEmployeesRolesNewRoute: typeof AdminEmployeesRolesNewRoute
}

const AdminEmployeesRouteChildren: AdminEmployeesRouteChildren = {
  AdminEmployeesRolesRoute: AdminEmployeesRolesRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminEmployeesRolesIdRoute: AdminEmployeesRolesIdRoute,
  AdminEmployeesRolesNewRoute: AdminEmployeesRolesNewRoute,
}

const AdminEmployeesRouteWithChildren = AdminEmployeesRoute._addFileChildren(
  AdminEmployeesRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsNewRoute: typeof AdminClientsNewRoute
  AdminDeliverablesIdRoute: typeof AdminDeliverablesIdRoute
  AdminDeliverablesIndexRoute: typeof AdminDeliverablesIndexRoute
  AdminAnalyticsEmployeeIdRoute: typeof AdminAnalyticsEmployeeIdRoute
  AdminDeliverablesClientsIdRoute: typeof AdminDeliverablesClientsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsNewRoute: AdminClientsNewRoute,
  AdminDeliverablesIdRoute: AdminDeliverablesIdRoute,
  AdminDeliverablesIndexRoute: AdminDeliverablesIndexRoute,
  AdminAnalyticsEmployeeIdRoute: AdminAnalyticsEmployeeIdRoute,
  AdminDeliverablesClientsIdRoute: AdminDeliverablesClientsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeRouteChildren {
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeGamesRoute: typeof EmployeeGamesRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeTasksRoute: typeof EmployeeTasksRoute
  EmployeeTeamRoute: typeof EmployeeTeamRoute
  EmployeeTimesheetRoute: typeof EmployeeTimesheetRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeeTasksTaskIdRoute: typeof EmployeeTasksTaskIdRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeGamesRoute: EmployeeGamesRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeTasksRoute: EmployeeTasksRoute,
  EmployeeTeamRoute: EmployeeTeamRoute,
  EmployeeTimesheetRoute: EmployeeTimesheetRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeeTasksTaskIdRoute: EmployeeTasksTaskIdRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface ManagerRouteChildren {
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ManagerProjectsRoute: typeof ManagerProjectsRoute
  ManagerTasksRoute: typeof ManagerTasksRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerDeliverablesIndexRoute: typeof ManagerDeliverablesIndexRoute
  ManagerAnalyticsEmployeeIdRoute: typeof ManagerAnalyticsEmployeeIdRoute
  ManagerProjectsIdSetupRoute: typeof ManagerProjectsIdSetupRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAnalyticsRoute: ManagerAnalyticsRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ManagerProjectsRoute: ManagerProjectsRoute,
  ManagerTasksRoute: ManagerTasksRoute,
  ManagerTeamRoute: ManagerTeamRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerDeliverablesIndexRoute: ManagerDeliverablesIndexRoute,
  ManagerAnalyticsEmployeeIdRoute: ManagerAnalyticsEmployeeIdRoute,
  ManagerProjectsIdSetupRoute: ManagerProjectsIdSetupRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
